Импортируем библиотеку NumPy

In [124]:
import numpy as np

Создаем массив из списка

In [125]:
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", arr_from_list)

Массив из списка: [1 2 3 4 5]


Создаем двумерный массив из вложенного списка

In [126]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив:\n", matrix_2d)

Двумерный массив:
 [[1 2 3]
 [4 5 6]]


Создаем массив из нулей

In [127]:
zeros_arr = np.zeros(5)
print("Массив из нулей:", zeros_arr)

Массив из нулей: [0. 0. 0. 0. 0.]


Создаем двумерный массив из единиц

In [128]:
ones_matrix = np.ones((2, 3))
print("Массив из единиц (2x3):\n", ones_matrix)

Массив из единиц (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]


Создаем массив с последовательностью чисел от 0 до 10 с шагом 2

In [129]:
range_arr = np.arange(0, 10, 2)
print("Массив с arange:", range_arr)

Массив с arange: [0 2 4 6 8]


Выводим размерность массива

In [130]:
print("Размерность matrix_2d:", matrix_2d.shape)

Размерность matrix_2d: (2, 3)


Выводим тип элементов массива

In [131]:
print("Тип данных matrix_2d:", matrix_2d.dtype)

Тип данных matrix_2d: int64


Выводим исходный одномерный массив

In [132]:
print("Исходный массив:", arr_from_list)

Исходный массив: [1 2 3 4 5]


Выводим первый элемент

In [133]:
print("Первый элемент:", arr_from_list[0])

Первый элемент: 1


Выводим элементы с индексом 1 до 3

In [134]:
print("Срез [1:4]:", arr_from_list[1:4])

Срез [1:4]: [2 3 4]


Выводим каждый второй элемент

In [135]:
print("Срез с шагом 2:", arr_from_list[::2])

Срез с шагом 2: [1 3 5]


Выводим исходный двумерный массив

In [136]:
print("\nДвумерный массив:\n", matrix_2d)


Двумерный массив:
 [[1 2 3]
 [4 5 6]]


Выводим 1 строку, 2 столбец

In [137]:
print("Элемент [1, 2]:", matrix_2d[1, 2])

Элемент [1, 2]: 6


Выводим все строки, столбец 1

In [138]:
print("Столбец 1:", matrix_2d[:, 1])

Столбец 1: [2 5]


Выводим подматрицу 2x2

In [139]:
print("Срез строк:\n", matrix_2d[0:2, 0:2])

Срез строк:
 [[1 2]
 [4 5]]


Создаем массивы a и b

In [140]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Выводим поэлементное сложение

In [141]:
print("Сложение a + b:", a + b) 

Сложение a + b: [5 7 9]


Выводим поэлементное умножение

In [142]:
print("Умножение a * b:", a * b)

Умножение a * b: [ 4 10 18]


Выводим среднее значение

In [143]:
print("Среднее значение:", np.mean(a))

Среднее значение: 2.0


Выводим стандартное отклонение

In [144]:
print("Стандартное отклонение:", np.std(a))

Стандартное отклонение: 0.816496580927726


Выводим максимальный элемент

In [145]:
print("Максимальный элемент:", np.max(a))

Максимальный элемент: 3


Выводим исходный двумерный массив

In [146]:
print("Двумерный массив:\n", matrix_2d)

Двумерный массив:
 [[1 2 3]
 [4 5 6]]


Выводим среднее по всему двумерному массиву

In [147]:
print("Среднее по всему массиву:", np.mean(matrix_2d))

Среднее по всему массиву: 3.5


Выводим среднее по столбцам

In [148]:
print("Среднее по столбцам:", np.mean(matrix_2d, axis=0))

Среднее по столбцам: [2.5 3.5 4.5]
